### ISSUE TITLE
Version indication on extensions pointless/confusing for Basilisk

### ISSUE THREAD

**Issue by wolfbeast** [Pale-Moon-Addons-Team/phoebus#100]
Extensions display a Firefox version range on the extension pages, e.g. `Works with Basilisk 52.0 to 56.*` which is confusing and doesn't really apply to Basilisk (since it doesn't use classic version numbers), listing Basilisk versions that don't exist.

Probably better to just drop this indicator for the Basilisk add-ons site?

**Comment by mattatobin** [comment]
Seems legit.
