### ISSUE TITLE
Got logged out after changing the password

### ISSUE THREAD

**Issue by thenamewastaken** [Pale-Moon-Addons-Team/phoebus#105]
I went to change my profile's password, and after clicking update, the authentication popup appeared, except that it was unresponsive. I could click on the fields and buttons, but I couldn't type anything.
The page behind was stuck in a loading state.
The password was changed correctly, and in fact it took me a couple tries to log in because I thought it was still using the old password.
If this move is intentional, please make a note somewhere (the panel homepage, or the settings page) that explain that we can get logged out under certain conditions and that it's intentional.
If not, something happened anyway and it might be a bug.

**Comment by mattatobin** [comment]
HTTP Auth sends headers with your credentials.. If they don't match you are challenged once again. I can't explain your unresponsiveness but that is simply how that works.
