### ISSUE TITLE
Compatibility with old links to extensions

### ISSUE THREAD

**Issue by JustOff** [Pale-Moon-Addons-Team/phoebus#106]
On the Pale Moon forum, as well as in other places, there are many links to extensions like `http(s)://addons.palemoon.org/extensions/name/`, which were previously automatically redirected to `http(s)://addons.palemoon.org/addon/name/`, but now this results in error 404.

Please restore these redirects to maintain integrity over time.

**Comment by mattatobin** [comment]
It should be still doing that.

**Comment by JustOff** [comment]
Is there any progress on the issue?

**Comment by mattatobin** [comment]
Not yet. I haven't been on light duty since Phoebus 2.0 landed. You could submit a patch against TRUNK if you want else wait until I get around to it.

**Comment by JustOff** [comment]
Thanks, I hope you fix it yourself in due time, because in order to propose a solution, I will be required to deal with the Phoebus logic almost from scratch.

**Comment by kn-yami** [comment]
I know nothing about PHP but I guess that something like this would be needed:
```php
// See if the slug exists in the category array and redirect if necessary
if (!array_key_exists($strSlug, classReadManifest::EXTENSION_CATEGORY_SLUGS)) {
	$strSlug = funcStripPath($arraySoftwareState['requestPath'], URI_ADDON_PAGE);
	if (!array_key_exists($strSlug, classReadManifest::EXTENSION_CATEGORY_SLUGS)) {
		funcSend404();
	}
	funcRedirect('/extensions/' . $strSlug);
}
```

**Comment by mattatobin** [comment]
No. You want to replace `funcSend404()` with `funcRedirect(`/addon/' . $strSlug)` on line 235

**Comment by kn-yami** [comment]
Oh, you are right, I did it backwards. For some reason I was thinking that I would need to redirect `/addon/slug` to `/extensions/slug`. Sorry.

**Comment by mattatobin** [comment]
Okay, I will fix this one liner today cause despite the fact that no one was willing to change the last three simple things despite the code being one liners and here with the direct solution being given..

I thank @kn-yami who attemped but I am very disappointed in the rest of everybody.

Maybe Binary Outcast just needs to eat Phoebus as a project.
