### ISSUE TITLE
Add ablity to track metadata on add-ons for developer statistics

### ISSUE THREAD

**Issue by mattatobin** [Pale-Moon-Addons-Team/phoebus#11]
Developers need a way to track information on how many people use their add-on and potentially other metadata

**Comment by mattatobin** [comment]
What information is important to developers?

Pale Moon current sends the following data that can be captured..

id (Add-on ID)
version (Add-on Version)
maxAppVersion (Currently installed Add-on Max Application Version)
status (Add-on status either enabled or disabled)
appID (Client GUID)
appVersion (Client Version)
appOS (User Operating system eg WINNT or LINUX)
appABI (User OS ABI eg WINNT_x86-msvc)
locale (Current Client Locale eg en-US)
currentAppVersion (Current Client Version)
updateType (Unknown)
compatMode (Normal or strict)

**Comment by wolfbeast** [comment]
I think for developers, it'd be important to know:
- Total number of users of their add-on, which can be approximated based on requests  
Note that this does not require individual profiling or tracking; a decent approximate can be created from the raw number of requests, as discussed on Jabber.
- appOS (to know if certain requests for OS-specific support are significant enough to prioritize, e.g. for skin support)
- Potentially currentAppVersion (to know if a significant number of people still use older versions of the browser or not); not sure if this is very prudent for Pale Moon, but might be interesting to know, especially if we're going to have breaking changes.
- locale (to know if it is worth to translate the add-on into a specific language)

For internal processing, so not exposed to the public/developers, the following needs to be used:
- Add-on version to split out statistics per add-on version in use (I'd suggest less granularity than AMO here, just the numbers of people on the current, latest version, and those who are not - if our stats are going to be monthly anyway, finer granularity is rather pointless)
- appID to discard anything that doesn't match Pale Moon; we already do this to prevent abuse, right?
- id to (obviously) be able to update the correct counter

**Comment by mattatobin** [comment]
The suggested estimation on a monthly basis is:

number of active users = (total requests in a month / 15) * 1.2

eg. 3000 requests divided by 15 (to account for every other day checking) times 1.2 (to account for partial months or times the browser isn't opened during the update window) = ABOUT 240 actual users... Which I feel is fair and what you suggested..

The same formula should be used for all metrics

Now.. How long should we be storing this for.. I was thinking no more than 3 or 6 months.. Saves on storage of the data and gives a good enough history for current usership.

I also think for Phoebus this data should be discarded unless it is specifically enabled for an add-on by a developer and some little blurb on the extension display page should notify users that this add-on has some basic metrics being collected and a page explaining exactly what is being collected and how it is used and make clear that we are dropping everything except that specific information on the floor.. To combat misconception of the privacy-ists,

**Comment by jez9999** [comment]
This sounds about right to me.  I think you guys know me view on the privacy aspect, though... I'm really struggling to see how anyone could use this info in an abusive manner so some kind of potentially scary warning to users about an addon "collecting metrics" seems OTT.

**Comment by mattatobin** [comment]
There won't be any abuse potential from us.. Most places that would collect this information would be doing it with highly granular data for each and every user including IP address..

I plan to simply drop anything not absolutely relevant on the floor and only do a slightly more complex counter system and use some fuzzy math to get broad estimations.. It won't be exact down to the last user just a fairly good indicator.. We nor developers need that kind of data to do development.. Just a good ball park figure is fine ;)

Also as an aside.. good ball park figures are easier to implement than an uber-profily-granular tracking system anyway so good for users, good for extension developers, and good for me who has to code the damn thing ;)

**Comment by jez9999** [comment]
That's the point I was making... if there's no abuse potential, putting in a message to the users is probably overkill.

**Comment by wolfbeast** [comment]
IMO it won't need a per-addon warning/notification. We just need to have a privacy policy outlining this behavior that is linked to in the footer of pages. I can make this write-up, if desired - I've wielded this sword often enough :)

**Comment by wolfbeast** [comment]
Also, as for retention: I'd say 6 months would be a good maximum, since we're doing things monthly - 3 wouldn't allow trends to be visible.
