### ISSUE TITLE
Where does one ask for AMO add-on ID verification?

### ISSUE THREAD

**Issue by alexander255** [Pale-Moon-Addons-Team/phoebus#110]
When trying to submit some of my old extensions, I got an error saying that the given add-on IDs had already been used on AMO and should write the “Pale Moon Add-Ons team or a Pheobus administrator” for verification. Unfortunately I have no who these people are and how to contact them.

Specifically, I'm interested in verifying the following IDs:

```
jid1-sZ7aKDCe4A2prQ@jetpack (Cookie Import/Export)
jid1-XGhxOf1M8UPpsQ@jetpack (Manage Search Engines button)
smart-referer@meh.paranoid.pk (Smart Referrer Classic)
```

Please kindly tell me what to do 🙂

**Comment by Lootyhoof** [comment]
That would be me. If you can send them to me via email (address in my GitHub profile) then I'll get these setup for you.

**Comment by Lootyhoof** [comment]
As this is an administration issue rather than a code one, and contact has already been made (check your emails) I'll be closing this.
