### ISSUE TITLE
Updates & additions for Known Incompatible Add-ons

### ISSUE THREAD

**Issue by ragues** [Pale-Moon-Addons-Team/phoebus#12]
I've found the following updates and additions for the above:

1) FireBug - workaround version given is v1.12.8.1; I could only find v1.12.8b1 (which works)
2) FireFTP - listed as incompatible - but V2.0.19-1 is compatible
3) Tree Style Tab - listed as incompatible - but old version 0.14.2014051101.1 works for me (not yet experienced any of the 'issues' mentioned in some of the threads)
4) OpenWith - not listed, but is incompatible. However can instead use "Open Link in Opera"; "Open Link in Chrome" / "Open Link in Google Chrome" and "Open in IE". Can't find anything for Safari.
5) Sticky Notes - not listed, but is incompatible. Internote can be used instead.
6) Tab Scope - not listed, but is incompatible. Tab Preview can be used instead
7) Update Scanner - not listed, but old v3.1.13.1 is compatible

**Comment by Lootyhoof** [comment]
>FireBug

v1.12.8.1 is actually listed as [1.12.8.1-signed] (https://addons.mozilla.org/en-US/firefox/addon/firebug/versions/1.12.8.1-signed) on AMO, though v1.12.8b1 is actually more recent.

>Sticky Notes

Version [0.4.6.1-signed] (https://addons.mozilla.org/en-US/firefox/addon/sticky-notes/versions/0.4.6.1-signed) is compatible.

>Tab Scope

Version [1.6.1.1-signed] (https://addons.mozilla.org/en-US/firefox/addon/tab-scope/versions/1.6.1.1-signed) is compatible.

**Comment by mattatobin** [comment]
Oh fantastic. Hey if someone wants to pull request on  /cmsms-hybrid/content/incompat.xhtml it would help.. Otherwise I will update it as soon as I can.. Thanks!

**Comment by LimboSlam** [comment]
@mattatobin: I didn't get the chance to report Privacy Badger properly, unless you figure out the situation and know what's up about it already. Until you reply back I will not add it yet here. This is the right place, right?

**Comment by mattatobin** [comment]
Not really no.. We know about privacy badger.. it has been a constant issue.

**Comment by LimboSlam** [comment]
Ok gotcha, I will wait then.

**Comment by ragues** [comment]
One correction:
4) Open With (by Geoff Lankow) - not listed, but is incompatible - but old version 5.6.3.1 is compatible. Not sure how I missed that first time around.

One addition:
8) Re-Pagination - not listed, but is incompatible - but old version 2013.03.18.1 works.

**Comment by Antonius32** [comment]
I have recently updated the list to include all extensions that were mentioned here.

@mattatobin: As far as I'm concerned, this issue can be closed.
