### ISSUE TITLE
[SQLize] Add basic Search functionality

### ISSUE THREAD

**Issue by mattatobin** [Pale-Moon-Addons-Team/phoebus#19]
When we searched off CMSMS-Hybrid we lost the search functionality.

We need to find a way to do search.. Obviously, yet another array is gonna be out of the question and so is parsing all manifest files.. Perhaps a search terms file for each extension could be created and then regularly parsed by a cron job to build a database of some manor and THAT could be parsed.

Still free text search and relating results is a complex prospect..

Any help on this would be appreciated.

**Comment by wolfbeast** [comment]
Perhaps using sphinx (currently in use on the forum) is an option? I'm not sure how easily that would be to integrate.
