### ISSUE TITLE
Add Unstable Channel for in-development versions of Add-ons

### ISSUE THREAD

**Issue by mattatobin** [Pale-Moon-Addons-Team/phoebus#25]
We want to offer an Unstable channel for add-ons based on Toolkit version and if a key is not none in manifest.

**Comment by mattatobin** [comment]
@agilbertson1977 @Lootyhoof 

I am questioning how wise this feature in 1.5 will be.. Since it is AUS dependent it could get very messy quick without more rigid requirements that simply aren't possible in an error prone manifest setup.

It would be my recommendation that this be pushed back to Phoebus 2.0 milestone unless we get a horde of people demanding it.

**Comment by mattatobin** [comment]
Andy has agreed to push it back.. Waiting for Ryan.

**Comment by Lootyhoof** [comment]
I'd be OK with pushing it back. It's not a must-have, and I've yet to encounter anyone to state otherwise.
