### ISSUE TITLE
Allow External Themes

### ISSUE THREAD

**Issue by mattatobin** [Pale-Moon-Addons-Team/phoebus#31]
It would be nice to allow themes to likewise have externals.

**Comment by mattatobin** [comment]
Blocks #32

**Comment by mattatobin** [comment]
@Lootyhoof It would be nice to have a theme to test external themes on. Please pick one and add it to the TRUNK category db.

**Comment by Lootyhoof** [comment]
This is now done. https://github.com/Pale-Moon-Addons-Team/phoebus/commit/f9e568c0ff71b23617fa32dbb66eef8f7d7f7c97
