### ISSUE TITLE
Add 'Tab Mix Plus' and 'uBlock Origin' to APMO

### ISSUE THREAD

**Issue by JustOff** [Pale-Moon-Addons-Team/phoebus#33]
'Tab Mix Plus' and 'uBlock Origin' extensions currently support Pale Moon natively (they use specific code for that and include proper targetApplication in indtall.rdf). I think we should add both of them to APMO as external add-ons.

**Comment by mattatobin** [comment]
Ideally the authors should make that decision but perhaps maybe.. The Add-ons Team will have to make that decision.

**Comment by mattatobin** [comment]
As a semi-related thing I am working on this page on the wiki for the Add-ons Site to update and expand what was originally a thread on the forum..

http://developer.palemoon.org/Add-ons:Site

**Comment by Lootyhoof** [comment]
I plan to add these and others soon.

**Comment by Lootyhoof** [comment]
These have now been added. I have not added Tab Mix Plus as this would cause confusion among users (the `minVersion` on AMO is 38), however I have added [Tab Utilities Phoenix](https://addons.mozilla.org/en-GB/firefox/addon/tab-utilities-phoenix/) instead. We would need to have Tab Mix Plus hosted with us to get it on the site, unless they change their `minVersion` on AMO.

I've also added uMatrix and Download Manager (S3), as these seem to be fan favourites lately.

**Comment by JustOff** [comment]
Thank you for the update! I think we definitely should find a way to add 'Tab Mix Plus' into APMO, because [the author makes special efforts to support Pale Moon](https://bitbucket.org/onemen/tabmixplus/commits/45b58143f082). I can confirm that the latest stable version ([5.0.2](https://addons.mozilla.org/en-US/firefox/addon/tab-mix-plus/versions/0.5.0.2)) is working perfectly with Pale Moon 27.x.

**Comment by Lootyhoof** [comment]
The only way it can be done is if the author approaches us to get it hosted. They can simply drop the same .xpi they otherwise use on AMO with us and it'll work; the issue with us is two-fold at the moment:

1. `minVersion` is too high on AMO. People will see that it is "not compatible" and avoid.
2. Due to 1 it won't update from AMO (as that is looking for the Firefox version, which we report as 27.9), so users won't be aware of future updates unless they continually check on AMO or the TMP site.

**Comment by JustOff** [comment]
Could you please consider to invite him? I can also do this, but I think that this case deserves direct attention from Add-ons Team.

**Comment by Lootyhoof** [comment]
You're right. I managed to find contact information for the author (namely, an email address), and got in touch. They quickly showed support for us! As such, it's now live and they have FTP access to update as they please:

https://addons.palemoon.org/extensions/tab-mix-plus/

**Comment by JustOff** [comment]
Thank you very much!
