### ISSUE TITLE
Show compatible browser version for each add-on on category pages

### ISSUE THREAD

**Issue by JustOff** [Pale-Moon-Addons-Team/phoebus#36]
Could you please consider to add this feature to APMO?

**Comment by mattatobin** [comment]
I don't want to clutter up category pages with information that should be on the add-ons page.

Given  #35 i really don't see a real reason to have it there anyway.

**Comment by mattatobin** [comment]
As an aside, it would be better not to abuse the issue system too much for this kind of thing.. If you would like to discuss your ideas.. You can come into IRC where the Add-ons Team hangs out. I am there too.

**Comment by wolfbeast** [comment]
Yeah let's not clutter up the category pages with details that belong on extension pages.
