### ISSUE TITLE
Bring Language Packs to the Add-ons Site

### ISSUE THREAD

**Issue by mattatobin** [Pale-Moon-Addons-Team/phoebus#37]
It would be really nice to be able to bring the language packs to the Add-ons Site seeing as they are add-ons after all.

Langpacks are treated as a special case in AUS but we have pretty much all the necessary info already to list them and link them to their current home on the release mirrors.

I am not really wanting to bring the XPI files them selves or offer old versions for them until Phoebus 2.0 but we may as well take advantage of the fact that we have all the metadata already to do this.

@wolfbeast

**Comment by wolfbeast** [comment]
You mean bringing the language pack page across to APMO? What about the necessary instructions for installing them?

**Comment by mattatobin** [comment]
All that would be included.

**Comment by wolfbeast** [comment]
No, by all means - the less i have to do manually to the main website for langpacks, the better. It's double work as it is now.
