### ISSUE TITLE
extensions.getAddons.get.url doesn't return proper results

### ISSUE THREAD

**Issue by JustOff** [Pale-Moon-Addons-Team/phoebus#42]
During the add-on installation AddonRepository.jsm [calls extensions.getAddons.get.url](http://xref.palemoon.org/palemoon-rel24/source/toolkit/mozapps/extensions/AddonRepository.jsm#730) to get add-on data. In Pale Moon such call uses [https://@APO_AM_URL@/internal/get?addonguid=%IDS%&os=%OS%&version=%VERSION%](http://xref.palemoon.org/palemoon-rel27/source/browser/branding/shared/pref/preferences.inc#101), but it doesn't return proper results.

For example, [https://addons.palemoon.org/integration/addon-manager/internal/get?addonguid=%7BB347DFB4-AC21-11DD-9016-B77D55D89593%7D&os=WINNT&version=27.9](https://addons.palemoon.org/integration/addon-manager/internal/get?addonguid=%7BB347DFB4-AC21-11DD-9016-B77D55D89593%7D&os=WINNT&version=27.9) returns: 
```
<?xml version="1.0" encoding="utf-8" ?>
<searchresults total_results="0">
</searchresults>
```

In fact here should be valid data if add-on hosted locally or redirection to [https://services.addons.mozilla.org/en-US/firefox/api/1.5/search/guid:%7BB347DFB4-AC21-11DD-9016-B77D55D89593%7D?src=firefox&appOS=WINNT&appVersion=27.9](https://services.addons.mozilla.org/en-US/firefox/api/1.5/search/guid:%7BB347DFB4-AC21-11DD-9016-B77D55D89593%7D?src=firefox&appOS=WINNT&appVersion=27.9) otherwise.

In most cases, it's not so critical, but has two unpleasant side effects:
1) If install.rdf contains '<em:localized>' blocks without '<em:name>' (it's rather common situation), then corresponding add-on displays 'null' instead of real extension name.
2) If install.rdf contains '<em:localized>' block for en-US without '<em:name>' (this is uncommon, but allowed), then corresponding add-on can't be installed at all.

I'm going to propose patch to XPIProvider.jsm which will fix both exceptions, but this does not eliminate the need to correct phoebus behavior.

**Comment by mattatobin** [comment]
We cannot re-enable this functionality to AMO because of #17. So your patch to XPIProvider becomes essential.

**Comment by JustOff** [comment]
Thanks, understood, so let's close this until someone found a better idea.
