### ISSUE TITLE
Rewrite Incompat Page

### ISSUE THREAD

**Issue by mattatobin** [Pale-Moon-Addons-Team/phoebus#5]
This page needs quite a bit of work.

**Comment by mattatobin** [comment]
aa7e56e7e00947343e10f364b422fc7e10e56f38 and e807d8fe80a8cf8847ca1df3c66b9f774af71f8f help matters but the page needs a superior design change.

I am open to any suggestions...

**Comment by wolfbeast** [comment]
"Mozilla Service Experaments are not supported on Pale Moon"
Please fix spelling of "experiments" :)

I'm not sure what else to suggest as far as layout goes. It may be served better with 2 columns instead of 3 so you don't have as much wrapping.

**Comment by mattatobin** [comment]
Both actual and alleged misspellings fixed in fede042674851cc98d785a48c0ed14c5aaaac76c

**Comment by mattatobin** [comment]
Antonius32 resolved this..
