### ISSUE TITLE
TRUNK should be refreshed

### ISSUE THREAD

**Issue by wolfbeast** [Pale-Moon-Addons-Team/phoebus#61]
With all the edits being done on RELEASE, the TRUNK branch got out of sync and has old db data/code in it. It should be refreshed to reflect the current state of things by copying recent edits across to it from RELEASE.

**Comment by mattatobin** [comment]
I have some more advanced plans for changes brewing in the back of my mind with regards to TRUNK.. I will sync db and current changes soon.

It isn't much of a consern but if someone wants to save me the trouble I am not gonna say no ;)
