### ISSUE TITLE
Internal search ignores spaces in extension names

### ISSUE THREAD

**Issue by JustOff** [Pale-Moon-Addons-Team/phoebus#62]
For example, when you try to find [Color My Tabs](https://addons.palemoon.org/addon/color-my-tabs/), browser sends request to `https://addons.palemoon.org/integration/addon-manager/internal/search?q=color%20my%20tabs&locale=en-US&os=WINNT&version=27.4.0` and here's how it's processed:

```
$ wget --spider "https://addons.palemoon.org/integration/addon-manager/internal/search?q=color%20my%20tabs&locale=en-US&os=WINNT&version=27.4.0"
Spider mode enabled. Check if remote file exists.
--2017-07-14 12:54:35--  https://addons.palemoon.org/integration/addon-manager/internal/search?q=color%20my%20tabs&locale=en-US&os=WINNT&version=27.4.0
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving addons.palemoon.org... 104.20.61.158, 104.20.60.158, 2400:cb00:2048:1::6814:3d9e, ...
Connecting to addons.palemoon.org|104.20.61.158|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: /integration/addon-manager/internal/search/?q=color%20my%20tabs&locale=en-US&os=WINNT&version=27.4.0 [following]
Spider mode enabled. Check if remote file exists.
--2017-07-14 12:54:36--  https://addons.palemoon.org/integration/addon-manager/internal/search/?q=color%20my%20tabs&locale=en-US&os=WINNT&version=27.4.0
Connecting to addons.palemoon.org|104.20.61.158|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://addons.palemoon.org/?component=integration&type=internal&request=search&q=color%20my%20tabs&locale=en-US&os=WINNT&version=27.4.0 [following]
Spider mode enabled. Check if remote file exists.
--2017-07-14 12:54:36--  https://addons.palemoon.org/?component=integration&type=internal&request=search&q=color%20my%20tabs&locale=en-US&os=WINNT&version=27.4.0
Connecting to addons.palemoon.org|104.20.61.158|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://services.addons.mozilla.org/en-US/firefox/api/1.5/search/colormytabs/all/10/WINNT/27.9 [following]
Spider mode enabled. Check if remote file exists.
--2017-07-14 12:54:37--  https://services.addons.mozilla.org/en-US/firefox/api/1.5/search/colormytabs/all/10/WINNT/27.9
Resolving services.addons.mozilla.org... 54.148.72.151, 54.149.96.195, 54.70.245.228
Connecting to services.addons.mozilla.org|54.148.72.151|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/xml]
Remote file exists.
```
The result: nothing was found locally, the request was redirected to AMO, and all the spaces were lost.

**Comment by mattatobin** [comment]
Try https://dev.addons.palemoon.org/?component=integration&type=internal&request=search&q=color%20my%20tabs&locale=en-US&os=WINNT&version=27.4.0

**Comment by JustOff** [comment]
Now on dev it redirects to AMO with spaces `https://services.addons.mozilla.org/en-US/firefox/api/1.5/search/color%20my%20tabs/all/10/WINNT/27.9`, but still misses it [locally](https://addons.palemoon.org/addon/color-my-tabs/).

**Comment by mattatobin** [comment]
-- **_ONCE AGAIN_** --
----
As an aside, as search is the only functioning internal integration function all requests go to AMO because we don't have a search facility of our own. When that changes we will loose the ability to get AMO search results which by then may not may not be important.

**Comment by JustOff** [comment]
Thanks for fixing the issue with spaces and for clarifying the current situation. And I hope we will not loose AMO search when local one is implemented, it seems quite logical to send search requests to AMO when local results are not found.

**Comment by mattatobin** [comment]
It will be impossible to maintain AMO for anything but AUS because there is no way to mix and mangle AMO results without the server its self making the request to AMO which could then be blacklisted for abusing any potential acceptable usage policies by Mozilla.

This is a FACT. The goal will be to eliminate our reliance on AMO going forward. AMO is becoming less relevant every day to us.

> Additionally, it is expected that eventually Mozilla's service will become unusable for purposes of providing updates to Firefox add-ons for Pale Moon users as they change how their service works. At any time we may discontinue sending unknown (to the Pale Moon Add-ons Site) update requests to Mozilla's Add-ons Site.

> At this time the Pale Moon Add-ons Team considers Mozilla's Add-ons Site and services to be legacy at best.

This applies to internal and external integration functions as much as it does to AUS.

**Comment by Lootyhoof** [comment]
I agree with Tobin's stance on this.

There will come a time when AMO isn't useful for us anymore, and while we don't know when exactly that will happen we do know that XUL extensions aren't exactly relevant there even now. Sooner or later we will need to make a stand on this, and stop relying on AMO entirely, for the good of anything XUL. 

Like it or not but it will happen. We need to be in control of our own ecosystem, and that requires moving away from AMO (be that either on our site or developer's self hosting).
