### ISSUE TITLE
Licenses should include a default Copyright license

### ISSUE THREAD

**Issue by wolfbeast** [Pale-Moon-Addons-Team/phoebus#67]
If no license is indicated or supplied by the add-on author, it should default to a fully-restricted copyright license.

`Copyright [Year] - [Author]`

This should link to a fully-restricted copyright statement with site redistribution permission like so:
```
This add-on is Copyrighted by its author(s); all rights reserved.

This add-on has been posted on this website by the author(s) or one of
their authorized agents with permission and consent for redistribution
to the public in unmodified form.

Modification, inclusion in a larger work, verbatim copying of (parts of)
this add-on's code and assets, and/or public redistribution of this
add-on without the express prior written permission of the author(s)
is prohibited.
```

**Comment by mattatobin** [comment]
When license is null a smalltext of (Unless otherwise indicated) should show up.. Otherwise make copyright a selectable license.
