### ISSUE TITLE
Move Regolith from Miami to New York

### ISSUE THREAD

**Issue by mattatobin** [Pale-Moon-Addons-Team/phoebus#68]
We need to move Regolith to New York.. I am thinking a complete server refresh would be best.. Though, the last server maintenance which updated us to CentOS 7.4 went smoothly and downtime was all of 3 minutes there is a lot of data that needs to be purged from our server and the complexity does need to be reduced as the server is still configured as a BinOC Server.

---

- [x] Arrange provisioning of New York server while still keeping Miami online until complete
- [x] Rewrite server configuration and split off from `aura-infra`
    - [x] Use `regolith.palemoon.org` internally rather than `regolith.server.binocnetwork.com`
    - [x] Set `addons-dev.palemoon.org` to New York server on MCP DNS
    - [x] Setup shell users
    - [x] Setup webmin
    - [x] Setup directory structure and upload required data
    - [x] Setup nginx and PHP 7.0
    - [x] Setup vsftpd
- [x] Test New York server
- [x] Set `addons.palemoon.org` to New York server on BinOC and MCP DNS
- [ ] Shut down and Destroy Miami instance

---

> Dear Matt,
> 
> I am writing to you because you have an Afterburst VM hosted in Miami. Last year, as part of ongoing improvements to our services, we moved to a new provider in the US who provide a superior network, hardware and support. Unfortunately they do not provide services in Miami, and as such we are shutting down the location.
> 
> We will be permanently shutting down our Miami servers on November 4th.
> 
> All customers in this location will be migrated to our New York datacenter. The migrations will happen throughout November 4th and we will let you know once your server is complete and the new IP is assigned. You should expect to see a significant performance improvement once this is complete.
> 
> If you would like to move earlier, or would like us to duplicate the server so you can migrate DNS/etc in your own time, please contact support. Additionally, if you would prefer not to move you can notify the support team and we will cancel the VM and subscription on November 4th.
> 
> Kind Regards,
> Nick / the Afterburst Team

**Comment by wolfbeast** [comment]
I'm assuming you're taking advantage of the duplication option then?

**Comment by mattatobin** [comment]
I doubt I will.. I am gonna ask if we can just have a naked server provisioned in New York and I am going to set it up from scratch.

**Comment by wolfbeast** [comment]
Just keep the afterburst folks in the loop with what you plan and they will help you with anything needed.

**Comment by mattatobin** [comment]
Blocks #70

**Comment by wolfbeast** [comment]
DNS set and propagated.

**Comment by mattatobin** [comment]
Afterburst says they will leave the old server accessible should we need something off it until they decommission the entire Miami setup.

As such I am setting this to fixed and closed and will check off the final item when that happens..
