### ISSUE TITLE
Rewrite and Enhance the Discover Pane page

### ISSUE THREAD

**Issue by mattatobin** [Pale-Moon-Addons-Team/phoebus#7]
Like the front page.. We should be promoting Pale Moon specific add-ons and themes here.

Also, the in-line MozCo styling needs to be moved to reusable classes in css. This page being one of the first entry points to the add-ons site should reflect more about what we offer and as Phoebus moves along, de-emphasizing AMO.

**Comment by mattatobin** [comment]
Of note the discover page is heavily cached by the CDN so image and style changes will need purged manually

**Comment by wolfbeast** [comment]
If you need developer mode in the CDN, let me know.

**Comment by mattatobin** [comment]
This has also been symlinked on a file system level to the repo copy

**Comment by mattatobin** [comment]
Fonts for the new discover page should be set in this order for best OS integration.

Segoe UI, Tahoma, Ubuntu, Cantarell, Lucida Grande, Aerial, sans

That covers Windows NT 6x, NT 5x, Ubuntu, Gnome generic, MacOS, whatever, and ultimate fallback

**Comment by mattatobin** [comment]
Blocks #16
