### ISSUE TITLE
Invalid characters in some externals slugs

### ISSUE THREAD

**Issue by mattatobin** [Pale-Moon-Addons-Team/phoebus#77]
The rules for slugs are as follows: a-z (lowercase) 0-9 and dash. No other characters are allowed.

**The following Externals have invalid slugs:**
- download-manager-(s3)
- opendownload²
- page-colors-&-fonts-buttons
- theme-font-&-size-changer
- who-stole-my-pictures?

I require that a member of the Add-ons Team to please correct them as soon as possible.

**Comment by mattatobin** [comment]
@Lootyhoof @FranklinDM

**Comment by Lootyhoof** [comment]
The slugs for these do not contain illegal characters...?

https://github.com/Pale-Moon-Addons-Team/phoebus/blob/RELEASE/db/categories.php#L114
https://github.com/Pale-Moon-Addons-Team/phoebus/blob/RELEASE/db/categories.php#L164
https://github.com/Pale-Moon-Addons-Team/phoebus/blob/RELEASE/db/categories.php#L96
https://github.com/Pale-Moon-Addons-Team/phoebus/blob/RELEASE/db/categories.php#L114
https://github.com/Pale-Moon-Addons-Team/phoebus/blob/RELEASE/db/categories.php#L293

**Comment by mattatobin** [comment]
It was an error in MY migration code.. I am a moron.

RESOLVED INVALID
