### ISSUE TITLE
Improve validator detection

### ISSUE THREAD

**Issue by Lootyhoof** [Pale-Moon-Addons-Team/phoebus#81]
Currently, it's possible to input a `<em:type>32</em:type>` `install.rdf` and it return without issue. We shouldn't be accepting these types as these are bundles (typically, theme + extension, though sometimes just several extensions). Example below (several `em:localized` entries omitted for brevity)...

````
<?xml version="1.0"?>
 
<RDF xmlns="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:em="http://www.mozilla.org/2004/em-rdf#">
 
  <Description about="urn:mozilla:install-manifest">
    <em:id>{a0d70d73-3faf-46c3-b98e-98e62085837f}</em:id>
    <em:version>2.0.0b1</em:version>
    <em:name>Compact Moon</em:name>
    <em:description>A very clean and compact theme with classic buttons that minimizes vertical space consumed by menus &amp; tool bars. Fork of "Classic Compact" by Ken Barbalace</em:description>
    <em:type>32</em:type>
    <em:internalName>compactmoon</em:internalName>

    <em:targetApplication>
      <Description>
        <!-- Pale Moon -->
        <em:id>{8de7fcbb-c55c-4fbe-bfc5-fc555c87dbc4}</em:id>
        <em:minVersion>27.5.0</em:minVersion>
        <em:maxVersion>27.*</em:maxVersion>
      </Description>
    </em:targetApplication>
  </Description>
</RDF>
````
Tobin also tells me to mention that icon detection is busted and that he would know what this means (because I don't!).

**Comment by Ascrod** [comment]
@mattatobin Commenting here as you requested.

https://github.com/Pale-Moon-Addons-Team/phoebus/blob/TRUNK/components/special/addonValidator.php#L140

From what I can tell, this will match IDs such as "@host". Technically this is supported by Mozilla. However, if you want to require at least one character before the @ symbol (e.g. "user@host"), the first asterisk needs to be a plus sign, like so:

`/[a-z0-9-\._]+\@[a-z0-9-\._]+/i`

**Comment by mattatobin** [comment]
Need to also check if there are infinity version parts in minVersion not JUST if it == '*'

**Comment by mattatobin** [comment]
This whole thing is being rewritten.. So closing...
